In [1]:
images_in_folder = 'test'

images_out_folder = 'D:/College/sem 5/ML/Project/test/test_coords'

csv_out_path = 'D:/College/sem 5/ML/Project/keypoint_test.csv'

import numpy as np
import pandas as pd

import tensorflow as tf



In [71]:
df=pd.read_csv(csv_out_path, header=None, names=["Class"]+[i for i in range(99)])
data=df.drop(['Class'], axis=1)

In [72]:
data=np.array(data)
data

array([[1298.75313,  306.42013, -136.64942, 1337.42649,  284.38647,
        -198.55515, 1344.87774,  288.19632, -198.56365, 1353.41835,
         292.61437, -198.44825, 1331.0923 ,  278.95982, -108.82148,
        1333.3128 ,  278.37036, -109.09005, 1336.31367,  278.14679,
        -109.37347, 1398.69953,  342.17947, -334.35559, 1379.52759,
         323.42915,   68.62944, 1301.83239,  352.54706, -179.54736,
        1291.42445,  345.98127,  -61.2235 , 1352.45258,  589.08719,
        -552.02814, 1289.26552,  510.55198,  328.45656, 1001.55716,
         651.50127, -584.98232, 1041.4492 ,  522.13118,  465.87255,
         733.01399,  530.32155, -383.0983 ,  780.57598,  479.09836,
         291.1966 ,  608.3844 ,  527.47707, -451.85841,  715.15348,
         471.59781,  270.39319,  620.97919,  487.6658 , -431.27715,
         729.34856,  453.75081,  158.5555 ,  654.80038,  492.04226,
        -369.18557,  751.65424,  460.75321,  234.41707, 1030.0248 ,
        1051.43808, -259.84654, 1027.07668,  915

In [73]:
data.shape

(1, 99)

In [74]:
from sklearn.preprocessing import StandardScaler
data=StandardScaler().fit_transform(data.reshape(-1,1))

In [75]:
data

array([[ 1.69612725],
       [-0.27567093],
       [-1.15606465],
       [ 1.77297248],
       [-0.31945254],
       [-1.27907336],
       [ 1.78777836],
       [-0.31188224],
       [-1.27909025],
       [ 1.80474883],
       [-0.30310343],
       [-1.27886094],
       [ 1.76038624],
       [-0.33023547],
       [-1.10076962],
       [ 1.76479844],
       [-0.33140675],
       [-1.10130327],
       [ 1.77076127],
       [-0.33185099],
       [-1.10186644],
       [ 1.89472402],
       [-0.20461595],
       [-1.54891328],
       [ 1.85662875],
       [-0.24187345],
       [-0.74816883],
       [ 1.70224584],
       [-0.18401521],
       [-1.24130426],
       [ 1.68156492],
       [-0.19706165],
       [-1.00619087],
       [ 1.80282981],
       [ 0.28599778],
       [-1.98143577],
       [ 1.67727506],
       [ 0.12994574],
       [-0.23188383],
       [ 1.10558912],
       [ 0.4100166 ],
       [-2.04691681],
       [ 1.18485591],
       [ 0.15295399],
       [ 0.04116625],
       [ 0

In [76]:
MODEL_PATH='D:\College\sem 5\ML\Project\MODEL\yoga\model.tflite'
interpreter = tf.lite.Interpreter(model_path=MODEL_PATH)
interpreter.allocate_tensors()

In [77]:
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [1]:
data=np.squeeze(data.T)

NameError: name 'np' is not defined

In [2]:
data

NameError: name 'data' is not defined

In [85]:
interpreter.set_tensor(input_details[0]['index'], np.array([data.T], dtype='float32'))

interpreter.invoke()

In [86]:
output_data = interpreter.get_tensor(output_details[0]['index'])
print(np.argmax(np.squeeze(output_data)))

1


In [88]:
output_data

array([[0.01837489, 0.8730195 , 0.07684432, 0.03176119]], dtype=float32)